### ISSUE TITLE
[Feat] 레이아웃 (헤더&푸터)

### ISSUE THREAD

**Issue by KiHwanChong** [Codeit-TripProduct-9team/FrontEnd#21]
## 어떤 컴포넌트인가요?
Layout
 - Header
 - Footer
 - Dropdown

## TODO
- [x] 헤더 로고 이미지 바꾸기
- [x] 페이지 url 변경
- [x] 드롭다운 메뉴
- [x] useClickOutside로 마우스가 드롭다운 바깥 클릭 시 드롭다운을 닫히게 하는 로직 분리 (다른 곳에서 재사용 가능)
- [x] 피그마 시안 나오면 푸터 변경하기

## 트러블 슈팅
컨텐츠가 빈 공간을 차지 못해서 푸터가 올라오는 에러.
layout에서 children에게 flex-grow 줘서 해결
```
  <div className="flex flex-col min-h-screen">
      <Header />
      <div className="flex-grow">{children}</div>
      <Footer />
    </div>
```
