### ISSUE TITLE
[Feat] travel-information

### ISSUE THREAD

**Issue by kkh000** [Codeit-TripProduct-9team/FrontEnd#24]
## 어떤페이지인가요
> 상세페이지 ('/travel-information')

## 어떤 컴포넌트인가요?
> 컴포넌트명 기재

## TODO
> 해야 할 일 기재
- [x] 유튜브 정보 받아오기 - 라이브러리 활용
- [x] 유튜브 조회수 , 생성일 - 정보 받아 오기
- [x] 나의 코스로 담기
- [x] 검색기능 - 세부페이지 내의 이동
- [x] 지도 - 현재 위치 기준으로 경로 출력
- [x] 지도 - 임의의 위치 기준으로 경로 출력
- [x] 메타태그 생성
- [x] 공유기능
- [x] 리뷰 - 수정, 삭제, 이미지

## 트러블 슈팅
> 컴포넌트 작성중 발생한 트러블 이슈가 있다면 댓글로 작성해주세요

## 레퍼런스
> 레퍼런스가 있다면 작성 해주세요
