### ISSUE TITLE
[Feat] Modal

### ISSUE THREAD

**Issue by naeun14** [Codeit-TripProduct-9team/FrontEnd#27]
## 어떤 컴포넌트인가요?
> Modal 컴포넌트: 기본 창은 비활성 상태로 전환되어 상호작용이 불가능하게 만드며 기본 창과 겹쳐져 가장 상단에 표시

여유가 될 시 toast 라이브러리 적용하면 좋을 것이라는 생각

## TODO
- [x] 모달 컴포넌트 사용법 jsdoc 남기기
- [x] 공통 컴포넌트로 분리
- [x] 내부 스타일 props로 적용 (tail merge 사용하여 기본값 등록)
- [x] 모달 외부 클릭시 닫힘 기능 추가

## 트러블 슈팅
> 컴포넌트 작성중 발생한 트러블 이슈가 있다면 댓글로 작성해주세요

## 레퍼런스
> 레퍼런스가 있다면 작성 해주세요
