### ISSUE TITLE
[Feat] 코스 리스트 페이지

### ISSUE THREAD

**Issue by naeun14** [Codeit-TripProduct-9team/FrontEnd#67]
## 어떤페이지인가요
 저장된 코스를 보여주는 페이지
/my-course

## TODO
- [x] 데이터를 받아 코스 보여주기 
- [x] 카드 컴포넌트를 눌렀을 때 description으로 넘어가기
- [x] 더보기 클릭시 모달로 상세 코스 설명으로 이동
- [x] 상세 코스 설명 - 모달 구현
- [x] 코스 수정
- [x] 코스 삭제

## 추가사항
> 상세 코스 설명 - 모달 구현, 코스 수정, 삭제
> userId 쿠키에 저장 후 불러오기
