### ISSUE TITLE
[Feat] 네이버 로그인 성공시 redirect

### ISSUE THREAD

**Issue by parkwoohyeok** [Codeit-TripProduct-9team/FrontEnd#7]
## 어떤페이지인가요
> signin

## TODO
> 해야 할 일 기재
- [x] 클라이언트 id 환경변수 등록
- [x] 네이버 로그인 성공시 백엔드에 code 값 post 보내기 
- [x] 백엔드 통신 성공시 main페이지로 리다이렉트 구현
